spring:
  cloud:
    gateway:
      routes:
        - id: accountModule
          uri: lb://account-service
          predicates:
            - Path=/users/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka